AWSTemplateFormatVersion: '2010-09-09'
Description: Service ECR repository
Parameters:

  RepositoryName:
    Type: String
    Description: RepositoryName

Resources:

  ##############################
  # ECR Repository
  ##############################

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Expire images older than 14 days",
                      "selection": {
                          "tagStatus": "untagged",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 14
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }